In [83]:
import pandas as pd
import glob
import string
from textblob import TextBlob
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sentence_transformers import SentenceTransformer
from sklearn.model_selection import train_test_split

Combining separte files into one

In [84]:
folder_path = "CSV files/*.csv"
all_files = glob.glob(folder_path)
df_list = [pd.read_csv(filename) for filename in all_files]
df = pd.concat(df_list, ignore_index=True)

In [85]:
df.head()

,,Time,Time.1,Place,Place.1,Place.2,Place.3,Place.4,Place.5,Place.6,...,Events.4,Events.5,Assessments,Assessments.1,Report 1,Report 1.1,Report 2,Report 2.1,Report 1.2,Unnamed: 125
0,ACN,Date,Local Time Of Day,Locale Reference,State Reference,Relative Position.Angle.Radial,Relative Position.Distance.Nautical Miles,Altitude.AGL.Single Value,Altitude.MSL.Single Value,Latitude / Longitude (UAS),...,When Detected,Result,Contributing Factors / Situations,Primary Problem,Narrative,Callback,Narrative,Callback,Synopsis,NaN
1,1714400,202001,0001-0600,ORD.Airport,IL,NaN,NaN,NaN,15000,NaN,...,In-flight,Air Traffic Control Issued New Clearance; Air ...,Aircraft; Company Policy,Company Policy,To be clear I did not have a lot going on and ...,NaN,NaN,NaN,A TRACON Departure Controller reported two air...,NaN
2,1714553,202001,1801-2400,ZHU.ARTCC,TX,NaN,NaN,NaN,14000,NaN,...,In-flight,Flight Crew Became Reoriented; General Physica...,Human Factors; Environment - Non Weather Related,Environment - Non Weather Related,While descending into PIB out of 14;000 ft. MS...,NaN,NaN,NaN,CRJ Captain reported that a laser shone repeat...,NaN
3,1714675,202001,1801-2400,ZZZ.ARTCC,US,NaN,NaN,NaN,9000,NaN,...,In-flight,Flight Crew Returned To Departure Airport; Fli...,Aircraft; Weather; Procedure,Weather,I was boarding the aircraft when a my destinat...,NaN,NaN,NaN,Pilot reported weather and a closed destinatio...,NaN
4,1714708,202001,0601-1200,ZZZ.Airport,US,NaN,NaN,0,NaN,NaN,...,In-flight,General None Reported / Taken,Procedure; Logbook Entry; Human Factors,Ambiguous,I had a ferry flight that went out of service ...,NaN,We departed ZZZ ferrying an un-airworthy aircr...,NaN,Air carrier Dispatcher and flight crew reporte...,NaN

In [86]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31141 entries, 0 to 31140
Columns: 126 entries,   to Unnamed: 125
dtypes: float64(1), str(125)
memory usage: 29.9 MB

In [87]:
df_1 = df.copy()

In [88]:
df_1 = df_1[['Assessments.1','Report 1']]

In [89]:
df_1.head()

,Assessments.1,Report 1
0,Primary Problem,Narrative
1,Company Policy,To be clear I did not have a lot going on and ...
2,Environment - Non Weather Related,While descending into PIB out of 14;000 ft. MS...
3,Weather,I was boarding the aircraft when a my destinat...
4,Ambiguous,I had a ferry flight that went out of service ...

In [90]:
df_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 31141 entries, 0 to 31140
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Assessments.1  31064 non-null  str
 1   Report 1       31138 non-null  str
dtypes: str(2)
memory usage: 486.7 KB

Checking for missing values

In [91]:
df_1.isnull().sum()/len(df_1) * 100

Assessments.1    0.247262
Report 1         0.009634
dtype: float64

Dropping Missing Values

In [92]:
df_1.dropna(inplace = True)

In [93]:
df_1.info()

<class 'pandas.DataFrame'>
Index: 31064 entries, 0 to 31140
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Assessments.1  31064 non-null  str
 1   Report 1       31064 non-null  str
dtypes: str(2)
memory usage: 728.1 KB

In [94]:
df_1.isnull().sum()/len(df_1) * 100

Assessments.1    0.0
Report 1         0.0
dtype: float64

Changing column name to first row

In [95]:
df_1.columns = df_1.iloc[0]
df_1 = df_1.drop(df.index[0])
df_1 = df_1.reset_index(drop=True)

In [96]:
df_1.head()

,Primary Problem,Narrative
0,Company Policy,To be clear I did not have a lot going on and ...
1,Environment - Non Weather Related,While descending into PIB out of 14;000 ft. MS...
2,Weather,I was boarding the aircraft when a my destinat...
3,Ambiguous,I had a ferry flight that went out of service ...
4,Aircraft,We were flying at 2500 ft. I started losing el...

In [97]:
df_1['Primary Problem'].value_counts()

Primary Problem
Human Factors                                         10823
Aircraft                                               9802
Procedure                                              2913
Ambiguous                                              2490
Weather                                                1059
Environment - Non Weather Related                       930
Airport                                                 786
Chart Or Publication                                    447
Airspace Structure                                      411
ATC Equipment / Nav Facility / Buildings                410
Company Policy                                          408
Software and Automation                                 177
Equipment / Tooling                                     103
Staffing                                                 96
MEL                                                      69
Incorrect / Not Installed / Unavailable Part             55
Manuals                                                  48
Logbook Entry                                            11
Primary Problem                                           8
Human Factors; Aircraft                                   4
Procedure; Aircraft                                       3
Weather; Human Factors                                    2
Company Policy; Aircraft                                  1
Aircraft; Aircraft                                        1
Ambiguous; Human Factors                                  1
Human Factors; Weather                                    1
Human Factors; Procedure                                  1
Chart Or Publication; Aircraft                            1
ATC Equipment / Nav Facility / Buildings; Aircraft        1
Aircraft; Airspace Structure                              1
Name: count, dtype: int64

Making narrative lowercase

In [98]:
df_1['Narrative'] = df_1['Narrative'].str.lower()
df_1['Narrative'][0]

"to be clear i did not have a lot going on and my complexity was not high. that is why this was a non-event. however; ord was super busy on two runways for a little bit and i am sure the tower was very busy landing 28c departing 28r and 22l. ground could have also been busy so that is why i put the information in there on complexity and amount of volume. here is what happened; we were on outboards at ord. there were a lot of aircraft going over the airport to balance the runways. i had a strip print and an aircraft depart and tag up. it was aircraft z. i was waiting for this aircraft to call on. i was waiting and waiting and making a plan. then the aircraft started climbing out of 5;000 feet; so i reached out and tried to turn the aircraft. he didn't turn or answer. i didn't know what happened or was happening. then i did it again. i was just about to call back to the tower and the position next to me was giving a briefing and they turned their aircraft to earnd.aircraft x. now they departed off of two different runways but i said to the guy next to me; 'hey; see if you have aircraft z by chance.' he did. so somehow aircraft z going westbound departing off of runway 28r was on the same frequency as aircraft x departing off of runway 22l. when the instruction for aircraft x was given; aircraft z and aircraft x took it. the controller said he didn't hear any indication that there was a step on each other or anything. during this time aircraft y also had departed and went to the incorrect frequency and that controller had to send him to the correct frequency. so there were 3 similar sounding aircraft on 1 frequency when only two were supposed to be there and they were all climbing when only two were supposed to be. we have tried to explain how bad incorrect frequency transfers could be and have kept records for months but it seems there is no sense of urgency at how bad this could be. the two aircraft came within approximately 4 miles from each other with one climbing blindly. that was very lucky.my recommendations would be to track these incidents when similar sounding aircraft are on the same frequency so that it can be brought to the airline dispatchers' attention and show the replay on what could happen and why they should be aware of the issue. however; when i have brought these things recently to our supervisors in the room; they have been advised that they should not keep track of things like this by [the] upper management operations managers and higher. they tell us we should report it when they could report it just like i can. this was luck this time that nothing happened. so i guess we will just open that swiss cheese holes with negligence and laziness and i will be in the seat one day when two planes come together and i may not be lucky like this time to be able to listen to the person next to me give the briefing. or we can go back to due diligence; attentiveness; and caring and report things like this and care about the operation. put effort on everyone's end to know when similar call signs are on frequencies or multiple frequencies. demand that dispatch works hard to not use call signs like this. or not; who cares any more right."

In [99]:
punc = string.punctuation

Removing punctuation

In [100]:
def remove_punc(text):
    return text.translate(str.maketrans('', '', punc))

In [101]:
df_1['Narrative'] = df_1['Narrative'].apply(remove_punc)

In [102]:
df_1['Narrative'][0]

'to be clear i did not have a lot going on and my complexity was not high that is why this was a nonevent however ord was super busy on two runways for a little bit and i am sure the tower was very busy landing 28c departing 28r and 22l ground could have also been busy so that is why i put the information in there on complexity and amount of volume here is what happened we were on outboards at ord there were a lot of aircraft going over the airport to balance the runways i had a strip print and an aircraft depart and tag up it was aircraft z i was waiting for this aircraft to call on i was waiting and waiting and making a plan then the aircraft started climbing out of 5000 feet so i reached out and tried to turn the aircraft he didnt turn or answer i didnt know what happened or was happening then i did it again i was just about to call back to the tower and the position next to me was giving a briefing and they turned their aircraft to earndaircraft x now they departed off of two different runways but i said to the guy next to me hey see if you have aircraft z by chance he did so somehow aircraft z going westbound departing off of runway 28r was on the same frequency as aircraft x departing off of runway 22l when the instruction for aircraft x was given aircraft z and aircraft x took it the controller said he didnt hear any indication that there was a step on each other or anything during this time aircraft y also had departed and went to the incorrect frequency and that controller had to send him to the correct frequency so there were 3 similar sounding aircraft on 1 frequency when only two were supposed to be there and they were all climbing when only two were supposed to be we have tried to explain how bad incorrect frequency transfers could be and have kept records for months but it seems there is no sense of urgency at how bad this could be the two aircraft came within approximately 4 miles from each other with one climbing blindly that was very luckymy recommendations would be to track these incidents when similar sounding aircraft are on the same frequency so that it can be brought to the airline dispatchers attention and show the replay on what could happen and why they should be aware of the issue however when i have brought these things recently to our supervisors in the room they have been advised that they should not keep track of things like this by the upper management operations managers and higher they tell us we should report it when they could report it just like i can this was luck this time that nothing happened so i guess we will just open that swiss cheese holes with negligence and laziness and i will be in the seat one day when two planes come together and i may not be lucky like this time to be able to listen to the person next to me give the briefing or we can go back to due diligence attentiveness and caring and report things like this and care about the operation put effort on everyones end to know when similar call signs are on frequencies or multiple frequencies demand that dispatch works hard to not use call signs like this or not who cares any more right'

Removing spelling mistakes from narrative

In [103]:
df_1['Narrative'] = df_1['Narrative'].apply(TextBlob)

Removing Stopwords

In [104]:
#nltk.download('stopwords')

In [105]:
stopword = stopwords.words('english')
def remove_stopwords(text):
    new_text = []
    
    for word in text.split():
        if word in stopword:
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [106]:
df_1['Narrative'] = df_1['Narrative'].apply(remove_stopwords)

In [107]:
df_1['Narrative'][0]

'  clear      lot going    complexity   high       nonevent however ord  super busy  two runways   little bit    sure  tower   busy landing 28c departing 28r  22l ground could  also  busy      put  information    complexity  amount  volume    happened    outboards  ord    lot  aircraft going   airport  balance  runways    strip print   aircraft depart  tag    aircraft z   waiting   aircraft  call    waiting  waiting  making  plan   aircraft started climbing   5000 feet   reached   tried  turn  aircraft  didnt turn  answer  didnt know  happened   happening           call back   tower   position next    giving  briefing   turned  aircraft  earndaircraft x   departed   two different runways   said   guy next   hey see    aircraft z  chance    somehow aircraft z going westbound departing   runway 28r     frequency  aircraft x departing   runway 22l   instruction  aircraft x  given aircraft z  aircraft x took   controller said  didnt hear  indication     step     anything   time aircraft  also  departed  went   incorrect frequency   controller   send    correct frequency    3 similar sounding aircraft  1 frequency   two  supposed        climbing   two  supposed     tried  explain  bad incorrect frequency transfers could    kept records  months   seems    sense  urgency   bad  could   two aircraft came within approximately 4 miles     one climbing blindly    luckymy recommendations would   track  incidents  similar sounding aircraft     frequency      brought   airline dispatchers attention  show  replay   could happen      aware   issue however    brought  things recently   supervisors   room    advised     keep track  things like    upper management operations managers  higher  tell us   report    could report   like     luck  time  nothing happened   guess    open  swiss cheese holes  negligence  laziness       seat one day  two planes come together   may   lucky like  time   able  listen   person next   give  briefing    go back  due diligence attentiveness  caring  report things like   care   operation put effort  everyones end  know  similar call signs   frequencies  multiple frequencies demand  dispatch works hard   use call signs like     cares   right'

Dealing with excessive whitespaces

In [108]:
df_1['Narrative'] = df_1['Narrative'].str.replace(r'\s+', ' ', regex=True).str.strip()

In [109]:
df_1['Narrative'][0]

'clear lot going complexity high nonevent however ord super busy two runways little bit sure tower busy landing 28c departing 28r 22l ground could also busy put information complexity amount volume happened outboards ord lot aircraft going airport balance runways strip print aircraft depart tag aircraft z waiting aircraft call waiting waiting making plan aircraft started climbing 5000 feet reached tried turn aircraft didnt turn answer didnt know happened happening call back tower position next giving briefing turned aircraft earndaircraft x departed two different runways said guy next hey see aircraft z chance somehow aircraft z going westbound departing runway 28r frequency aircraft x departing runway 22l instruction aircraft x given aircraft z aircraft x took controller said didnt hear indication step anything time aircraft also departed went incorrect frequency controller send correct frequency 3 similar sounding aircraft 1 frequency two supposed climbing two supposed tried explain bad incorrect frequency transfers could kept records months seems sense urgency bad could two aircraft came within approximately 4 miles one climbing blindly luckymy recommendations would track incidents similar sounding aircraft frequency brought airline dispatchers attention show replay could happen aware issue however brought things recently supervisors room advised keep track things like upper management operations managers higher tell us report could report like luck time nothing happened guess open swiss cheese holes negligence laziness seat one day two planes come together may lucky like time able listen person next give briefing go back due diligence attentiveness caring report things like care operation put effort everyones end know similar call signs frequencies multiple frequencies demand dispatch works hard use call signs like cares right'

In [110]:
#nltk.download('punkt')
#nltk.download('punkt_tab')

Tokenization

In [111]:
df_1['Narrative'] = df_1['Narrative'].apply(word_tokenize)

In [112]:
df_1['Narrative'][0]

['clear',
 'lot',
 'going',
 'complexity',
 'high',
 'nonevent',
 'however',
 'ord',
 'super',
 'busy',
 'two',
 'runways',
 'little',
 'bit',
 'sure',
 'tower',
 'busy',
 'landing',
 '28c',
 'departing',
 '28r',
 '22l',
 'ground',
 'could',
 'also',
 'busy',
 'put',
 'information',
 'complexity',
 'amount',
 'volume',
 'happened',
 'outboards',
 'ord',
 'lot',
 'aircraft',
 'going',
 'airport',
 'balance',
 'runways',
 'strip',
 'print',
 'aircraft',
 'depart',
 'tag',
 'aircraft',
 'z',
 'waiting',
 'aircraft',
 'call',
 'waiting',
 'waiting',
 'making',
 'plan',
 'aircraft',
 'started',
 'climbing',
 '5000',
 'feet',
 'reached',
 'tried',
 'turn',
 'aircraft',
 'didnt',
 'turn',
 'answer',
 'didnt',
 'know',
 'happened',
 'happening',
 'call',
 'back',
 'tower',
 'position',
 'next',
 'giving',
 'briefing',
 'turned',
 'aircraft',
 'earndaircraft',
 'x',
 'departed',
 'two',
 'different',
 'runways',
 'said',
 'guy',
 'next',
 'hey',
 'see',
 'aircraft',
 'z',
 'chance',
 'somehow',
 'aircraft',
 'z',
 'going',
 'westbound',
 'departing',
 'runway',
 '28r',
 'frequency',
 'aircraft',
 'x',
 'departing',
 'runway',
 '22l',
 'instruction',
 'aircraft',
 'x',
 'given',
 'aircraft',
 'z',
 'aircraft',
 'x',
 'took',
 'controller',
 'said',
 'didnt',
 'hear',
 'indication',
 'step',
 'anything',
 'time',
 'aircraft',
 'also',
 'departed',
 'went',
 'incorrect',
 'frequency',
 'controller',
 'send',
 'correct',
 'frequency',
 '3',
 'similar',
 'sounding',
 'aircraft',
 '1',
 'frequency',
 'two',
 'supposed',
 'climbing',
 'two',
 'supposed',
 'tried',
 'explain',
 'bad',
 'incorrect',
 'frequency',
 'transfers',
 'could',
 'kept',
 'records',
 'months',
 'seems',
 'sense',
 'urgency',
 'bad',
 'could',
 'two',
 'aircraft',
 'came',
 'within',
 'approximately',
 '4',
 'miles',
 'one',
 'climbing',
 'blindly',
 'luckymy',
 'recommendations',
 'would',
 'track',
 'incidents',
 'similar',
 'sounding',
 'aircraft',
 'frequency',
 'brought',
 'airline',
 'dispatchers',
 'attention',
 'show',
 'replay',
 'could',
 'happen',
 'aware',
 'issue',
 'however',
 'brought',
 'things',
 'recently',
 'supervisors',
 'room',
 'advised',
 'keep',
 'track',
 'things',
 'like',
 'upper',
 'management',
 'operations',
 'managers',
 'higher',
 'tell',
 'us',
 'report',
 'could',
 'report',
 'like',
 'luck',
 'time',
 'nothing',
 'happened',
 'guess',
 'open',
 'swiss',
 'cheese',
 'holes',
 'negligence',
 'laziness',
 'seat',
 'one',
 'day',
 'two',
 'planes',
 'come',
 'together',
 'may',
 'lucky',
 'like',
 'time',
 'able',
 'listen',
 'person',
 'next',
 'give',
 'briefing',
 'go',
 'back',
 'due',
 'diligence',
 'attentiveness',
 'caring',
 'report',
 'things',
 'like',
 'care',
 'operation',
 'put',
 'effort',
 'everyones',
 'end',
 'know',
 'similar',
 'call',
 'signs',
 'frequencies',
 'multiple',
 'frequencies',
 'demand',
 'dispatch',
 'works',
 'hard',
 'use',
 'call',
 'signs',
 'like',
 'cares',
 'right']

Lemmitization

In [113]:
#nltk.download('wordnet')
#nltk.download('omw-1.4')

In [114]:
#nltk.download('averaged_perceptron_tagger', force=True)

In [115]:
lemmatizer = WordNetLemmatizer()

In [116]:
df_1['Narrative'] = df_1['Narrative'].apply(
    lambda x: [lemmatizer.lemmatize(word) for word in x]
)

In [117]:
df_1['Narrative'][0]

['clear',
 'lot',
 'going',
 'complexity',
 'high',
 'nonevent',
 'however',
 'ord',
 'super',
 'busy',
 'two',
 'runway',
 'little',
 'bit',
 'sure',
 'tower',
 'busy',
 'landing',
 '28c',
 'departing',
 '28r',
 '22l',
 'ground',
 'could',
 'also',
 'busy',
 'put',
 'information',
 'complexity',
 'amount',
 'volume',
 'happened',
 'outboard',
 'ord',
 'lot',
 'aircraft',
 'going',
 'airport',
 'balance',
 'runway',
 'strip',
 'print',
 'aircraft',
 'depart',
 'tag',
 'aircraft',
 'z',
 'waiting',
 'aircraft',
 'call',
 'waiting',
 'waiting',
 'making',
 'plan',
 'aircraft',
 'started',
 'climbing',
 '5000',
 'foot',
 'reached',
 'tried',
 'turn',
 'aircraft',
 'didnt',
 'turn',
 'answer',
 'didnt',
 'know',
 'happened',
 'happening',
 'call',
 'back',
 'tower',
 'position',
 'next',
 'giving',
 'briefing',
 'turned',
 'aircraft',
 'earndaircraft',
 'x',
 'departed',
 'two',
 'different',
 'runway',
 'said',
 'guy',
 'next',
 'hey',
 'see',
 'aircraft',
 'z',
 'chance',
 'somehow',
 'aircraft',
 'z',
 'going',
 'westbound',
 'departing',
 'runway',
 '28r',
 'frequency',
 'aircraft',
 'x',
 'departing',
 'runway',
 '22l',
 'instruction',
 'aircraft',
 'x',
 'given',
 'aircraft',
 'z',
 'aircraft',
 'x',
 'took',
 'controller',
 'said',
 'didnt',
 'hear',
 'indication',
 'step',
 'anything',
 'time',
 'aircraft',
 'also',
 'departed',
 'went',
 'incorrect',
 'frequency',
 'controller',
 'send',
 'correct',
 'frequency',
 '3',
 'similar',
 'sounding',
 'aircraft',
 '1',
 'frequency',
 'two',
 'supposed',
 'climbing',
 'two',
 'supposed',
 'tried',
 'explain',
 'bad',
 'incorrect',
 'frequency',
 'transfer',
 'could',
 'kept',
 'record',
 'month',
 'seems',
 'sense',
 'urgency',
 'bad',
 'could',
 'two',
 'aircraft',
 'came',
 'within',
 'approximately',
 '4',
 'mile',
 'one',
 'climbing',
 'blindly',
 'luckymy',
 'recommendation',
 'would',
 'track',
 'incident',
 'similar',
 'sounding',
 'aircraft',
 'frequency',
 'brought',
 'airline',
 'dispatcher',
 'attention',
 'show',
 'replay',
 'could',
 'happen',
 'aware',
 'issue',
 'however',
 'brought',
 'thing',
 'recently',
 'supervisor',
 'room',
 'advised',
 'keep',
 'track',
 'thing',
 'like',
 'upper',
 'management',
 'operation',
 'manager',
 'higher',
 'tell',
 'u',
 'report',
 'could',
 'report',
 'like',
 'luck',
 'time',
 'nothing',
 'happened',
 'guess',
 'open',
 'swiss',
 'cheese',
 'hole',
 'negligence',
 'laziness',
 'seat',
 'one',
 'day',
 'two',
 'plane',
 'come',
 'together',
 'may',
 'lucky',
 'like',
 'time',
 'able',
 'listen',
 'person',
 'next',
 'give',
 'briefing',
 'go',
 'back',
 'due',
 'diligence',
 'attentiveness',
 'caring',
 'report',
 'thing',
 'like',
 'care',
 'operation',
 'put',
 'effort',
 'everyones',
 'end',
 'know',
 'similar',
 'call',
 'sign',
 'frequency',
 'multiple',
 'frequency',
 'demand',
 'dispatch',
 'work',
 'hard',
 'use',
 'call',
 'sign',
 'like',
 'care',
 'right']

Train test split

In [119]:
X = df_1['Narrative'].copy()
y = df_1['Primary Problem'].copy()
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=42)